routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::domain('admin.penal.ga')->name('admin.')->middleware('verified','admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::prefix('organization')->name('organization.')->group(function () {
        Route::get('/', 'Admin\OrganizationController@index')->name('index');
        Route::get('/list', 'Admin\OrganizationController@index')->name('list');
        Route::get('/create', 'Admin\OrganizationController@create')->name('create');
        Route::post('/create', 'Admin\OrganizationController@store')->name('store');
        Route::get('/{organization}', 'Admin\OrganizationController@read')->name('read');
        Route::get('/{organization}/edit', 'Admin\OrganizationController@edit')->name('edit');
        Route::post('/{organization}/edit', 'Admin\OrganizationController@update')->name('update');
        Route::get('/{organization}/delete', 'Admin\OrganizationController@destroy')->name('delete');
        Route::post('/create', 'Admin\OrganizationController@store')->name('store');
        Route::prefix('vuz')->name('vuz.')->group(function(){
            Route::get('/{organization}/editProhodBalls', 'Admin\OrganizationController@vuzEditProhodBalls')->name('editProhodBalls');
            Route::post('/{organization}/updateProhodBalls', 'Admin\OrganizationController@vuzUpdateProhodBalls')->name('updateProhodBalls');
        });

    });
    /*Route::prefix('vuzFaculty')->name('vuz_faculty.')->group(function () {
        Route::get('/vuz/{vuz}', 'Admin\VuzFacultyController@index')->name('index');
        Route::get('/vuz/{vuz}/list', 'Admin\VuzFacultyController@index')->name('list');
        Route::get('/vuz/{vuz}/create', 'Admin\VuzFacultyController@create')->name('create');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzFacultyController@store')->name('store');
        Route::get('/{vuzFaculty}', 'Admin\VuzFacultyController@read')->name('read');
        Route::get('/{vuzFaculty}/edit', 'Admin\VuzFacultyController@edit')->name('edit');
        Route::post('/{vuzFaculty}/edit', 'Admin\VuzFacultyController@update')->name('update');
        Route::get('/{vuzFaculty}/delete', 'Admin\VuzFacultyController@destroy')->name('delete');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzFacultyController@store')->name('store');
    });*/
    Route::prefix('vuzDivision')->name('vuz_division.')->group(function () {
        Route::get('/vuz/{vuz}', 'Admin\VuzDivisionController@index')->name('index');
        Route::get('/vuz/{vuz}/list', 'Admin\VuzDivisionController@index')->name('list');
        Route::get('/vuz/{vuz}/create', 'Admin\VuzDivisionController@create')->name('create');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzDivisionController@store')->name('store');
        Route::get('/{vuzDivision}', 'Admin\VuzDivisionController@read')->name('read');
        Route::get('/{vuzDivision}/edit', 'Admin\VuzDivisionController@edit')->name('edit');
        Route::post('/{vuzDivision}/edit', 'Admin\VuzDivisionController@update')->name('update');
        Route::get('/{vuzDivision}/delete', 'Admin\VuzDivisionController@destroy')->name('delete');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzDivisionController@store')->name('store');
    });
    Route::prefix('speciality')->name('speciality.')->group(function () {
        Route::get('/', 'AdminController@specialityIndex')->name('index');
        Route::get('/list', 'AdminController@specialityIndex')->name('list');
        Route::get('/create', 'AdminController@specialityCreate')->name('create');
        Route::post('/create', 'AdminController@specialityStore')->name('store');
        Route::get('/{speciality}', 'AdminController@specialityRead')->name('read');
        Route::get('/{speciality}/edit', 'AdminController@specialityEdit')->name('edit');
        Route::post('/{speciality}/edit', 'AdminController@specialityUpdate')->name('update');
        Route::get('/{speciality}/delete', 'AdminController@specialityDestroy')->name('delete');
        Route::post('/create', 'AdminController@specialityStore')->name('store');
    });
    Route::prefix('eduForm')->name('eduForm.')->group(function () {
        Route::get('/', 'AdminController@eduFormIndex')->name('index');
        Route::get('/list', 'AdminController@eduFormIndex')->name('list');
        Route::get('/create', 'AdminController@eduFormCreate')->name('create');
        Route::post('/create', 'AdminController@eduFormStore')->name('store');
        Route::get('/{eduForm}', 'AdminController@eduFormRead')->name('read');
        Route::get('/{eduForm}/edit', 'AdminController@eduFormEdit')->name('edit');
        Route::post('/{eduForm}/edit', 'AdminController@eduFormUpdate')->name('update');
        Route::get('/{eduForm}/delete', 'AdminController@eduFormDestroy')->name('delete');
    });

    Route::prefix('profile')->name('profile.')->group(function () {
        Route::get('/', 'AdminController@profileIndex')->name('index');
        Route::post('/', 'AdminController@profileUpdate')->name('update');
    });
    Route::prefix('post')->name('post.')->group(function () {
        Route::get('/{post}', 'Admin\PostController@read')->name('read');
        Route::get('/{post}/edit', 'Admin\PostController@edit')->name('edit');
        Route::post('/{post}/edit', 'Admin\PostController@update')->name('update');
        Route::get('/post}/delete', 'Admin\PostController@destroy')->name('delete');
        Route::get('/{parent_type}/{parent_id}', 'Admin\PostController@index')->name('index');
        Route::get('/{parent_type}/{parent_id}/list', 'Admin\PostController@index')->name('list');
        Route::get('/{parent_type}/{parent_id}/create', 'Admin\PostController@create')->name('create');
        Route::post('/{parent_type}/{parent_id}/create', 'Admin\PostController@store')->name('store');
    });
    Route::prefix('exam')->name('exam.')->group(function () {
        Route::get('/', 'AdminController@examIndex')->name('index');
        Route::get('/list', 'AdminController@examIndex')->name('list');
        Route::get('/create', 'AdminController@examCreate')->name('create');
        Route::post('/create', 'AdminController@examStore')->name('store');
        Route::get('/{exam}', 'AdminController@examRead')->name('read');
        Route::get('/{exam}/edit', 'AdminController@examEdit')->name('edit');
        Route::post('/{exam}/edit', 'AdminController@examUpdate')->name('update');
        Route::get('/{exam}/delete', 'AdminController@examDestroy')->name('delete');
    });
    Route::prefix('subject')->name('subject.')->group(function () {
        Route::get('/e{exam}/', 'AdminController@subjectIndex')->name('index');
        Route::get('/e{exam}/list', 'AdminController@subjectIndex')->name('list');
        Route::get('/e{exam}/create', 'AdminController@subjectCreate')->name('create');
        Route::post('/e{exam}/create', 'AdminController@subjectStore')->name('store');
        Route::get('/{subject}', 'AdminController@subjectRead')->name('read');
        Route::get('/{subject}/edit', 'AdminController@subjectEdit')->name('edit');
        Route::post('/{subject}/edit', 'AdminController@subjectUpdate')->name('update');
        Route::get('/{subject}/delete', 'AdminController@subjectDestroy')->name('delete');
    });
    Route::prefix('theme')->name('theme.')->group(function () {
        Route::get('/s{subject}/', 'AdminController@themeIndex')->name('index');
        Route::get('/s{subject}/list', 'AdminController@themeIndex')->name('list');
        Route::get('/s{subject}/create', 'AdminController@themeCreate')->name('create');
        Route::post('/s{subject}/create', 'AdminController@themeStore')->name('store');
        Route::get('/{theme}', 'AdminController@themeRead')->name('read');
        Route::get('/{theme}/edit', 'AdminController@themeEdit')->name('edit');
        Route::post('/{theme}/edit', 'AdminController@themeUpdate')->name('update');
        Route::get('/{theme}/delete', 'AdminController@themeDestroy')->name('delete');
    });
    Route::prefix('prot')->name('prot.')->group(function () {
        Route::get('/th{theme}/create', 'AdminController@protCreate')->name('create');
        Route::post('/th{theme}/create', 'AdminController@protStore')->name('store');
        Route::get('/{prot}', 'AdminController@protRead')->name('read');
        Route::get('/{prot}/edit', 'AdminController@protEdit')->name('edit');
        Route::post('/{prot}/edit', 'AdminController@protUpdate')->name('update');
        Route::get('/{prot}/delete', 'AdminController@protDestroy')->name('delete');
    });
    Route::prefix('page')->name('page.')->group(function () {
        Route::get('/create', 'AdminController@pageCreate')->name('create');
        Route::post('/create', 'AdminController@pageStore')->name('store');
        Route::get('/list', 'AdminController@pageIndex')->name('list');
        Route::get('/{page}', 'AdminController@pageRead')->name('read');
        Route::get('/{page}/edit', 'AdminController@pageEdit')->name('edit');
        Route::post('/{page}/edit', 'AdminController@pageUpdate')->name('update');
        Route::get('/{page}/delete', 'AdminController@pageDestroy')->name('delete');
        Route::get('/', 'AdminController@pageIndex')->name('index');
    });
    Route::prefix('media-size')->name('mediaSize.')->group(function () {
        Route::get('/', 'Admin\MediaSizeController@index')->name('index');
        Route::get('/list', 'Admin\MediaSizeController@index')->name('list');
        Route::get('/create', 'Admin\MediaSizeController@create')->name('create');

resources/views/feed.blade.php
@extends('layouts.app')
@section('head')
    <title>Всё для школьников и абитуриентов на Пенале</title>

@endsection
@section('content')
    <div class="fullblock mb-3 p-3" style="background-image:linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.6)),url(/img/bg.jpg);">
        <div class="container ma">
            <h1 class="display-4 mb-4" data-aos="fade-right"> Подпишись на Пенал!
            </h1>
            <h3 class="mb-3" data-aos="fade-right" data-aos-delay="300">
                <i class="fas fa-calendar-check fa-fw text-warning fa-lg mr-1"></i>
                будь в курсе всех событий в мире образования,
            </h3>
            <h3 class="mb-3" data-aos="fade-right" data-aos-delay="600">
                <i class="fas fa-video fa-fw text-warning fa-lg mr-1"></i>
                смотри разбор заданий ЕГЭ и ОГЭ преподавателями-экспертами,
            </h3>
            <h3 class="mb-4" data-aos="fade-right" data-aos-delay="900">
                <i class="fas fa-piggy-bank fa-fw text-warning fa-lg mr-1"></i>
                получай скидки от наших партнеров!
            </h3>
            <a data-aos-delay="1200" data-aos="zoom-in" href="#" class="btn btn-warning font-weight-bold col-md-3" style="color: #000;">ПОДПИСАТЬСЯ</a>
        </div>
    </div>

    @guest
    <div class="container">
        <div class="alert alert-warning">
            <b>Персональная лента отключена!</b> Авторизируйтесь на Пенале, чтобы пользоваться всеми возможностями системы.
        </div>
    </div>
    @endguest
    <div class="container ma row">
        @foreach($posts as $post)
            @include('shared.post',[
            'post'=>$post
            ])
        @endforeach
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/post.blade.php
@extends('layouts.app')
@section('head')
    <title>{{$post->title}} на Пенале</title>
    <meta description="{{$post->description}}">
    <meta keywords="{{$post->keywords}}">
@endsection
@section('content')
    <div class="fullblock mb-5" style="background-image:linear-gradient(#0007,#0009),url({{$post->preview_photo}});">
        <div class="container pt-5 pb-5">
            <div class="float-right">
                <a href="{{route('organization.read',[
                    'organization'=>$post->parent->id
                ])}}" class="h4 text-white">

                    {{$post->parent->name}}
                </a>
            </div>

            <p> {{$post->created_at}}</p>
            <h1 class="display-4">{{$post->title}}</h1>
            {{$post->description}}
        </div>
    </div>

    <section class="container ma">
        <article class="mb-4">
            <h1>
               {{$post->title}}
            </h1>
            {!! $post->context !!}
        </article>
       {{-- <div>
            <p class="h5">
                {{$post->views}} просмотров
            </p>
        </div>--}}

    </section>


@endsection