routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::domain('admin.penal.ga')->name('admin.')->middleware('verified','admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::prefix('organization')->name('organization.')->group(function () {
        Route::get('/', 'Admin\OrganizationController@index')->name('index');
        Route::get('/list', 'Admin\OrganizationController@index')->name('list');
        Route::get('/create', 'Admin\OrganizationController@create')->name('create');
        Route::post('/create', 'Admin\OrganizationController@store')->name('store');
        Route::get('/{organization}', 'Admin\OrganizationController@read')->name('read');
        Route::get('/{organization}/edit', 'Admin\OrganizationController@edit')->name('edit');
        Route::post('/{organization}/edit', 'Admin\OrganizationController@update')->name('update');
        Route::get('/{organization}/delete', 'Admin\OrganizationController@destroy')->name('delete');
        Route::post('/create', 'Admin\OrganizationController@store')->name('store');
        Route::prefix('vuz')->name('vuz.')->group(function(){
            Route::get('/{organization}/editProhodBalls', 'Admin\OrganizationController@vuzEditProhodBalls')->name('editProhodBalls');
            Route::post('/{organization}/updateProhodBalls', 'Admin\OrganizationController@vuzUpdateProhodBalls')->name('updateProhodBalls');
        });

    });
    /*Route::prefix('vuzFaculty')->name('vuz_faculty.')->group(function () {
        Route::get('/vuz/{vuz}', 'Admin\VuzFacultyController@index')->name('index');
        Route::get('/vuz/{vuz}/list', 'Admin\VuzFacultyController@index')->name('list');
        Route::get('/vuz/{vuz}/create', 'Admin\VuzFacultyController@create')->name('create');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzFacultyController@store')->name('store');
        Route::get('/{vuzFaculty}', 'Admin\VuzFacultyController@read')->name('read');
        Route::get('/{vuzFaculty}/edit', 'Admin\VuzFacultyController@edit')->name('edit');
        Route::post('/{vuzFaculty}/edit', 'Admin\VuzFacultyController@update')->name('update');
        Route::get('/{vuzFaculty}/delete', 'Admin\VuzFacultyController@destroy')->name('delete');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzFacultyController@store')->name('store');
    });*/
    Route::prefix('vuzDivision')->name('vuz_division.')->group(function () {
        Route::get('/vuz/{vuz}', 'Admin\VuzDivisionController@index')->name('index');
        Route::get('/vuz/{vuz}/list', 'Admin\VuzDivisionController@index')->name('list');
        Route::get('/vuz/{vuz}/create', 'Admin\VuzDivisionController@create')->name('create');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzDivisionController@store')->name('store');
        Route::get('/{vuzDivision}', 'Admin\VuzDivisionController@read')->name('read');
        Route::get('/{vuzDivision}/edit', 'Admin\VuzDivisionController@edit')->name('edit');
        Route::post('/{vuzDivision}/edit', 'Admin\VuzDivisionController@update')->name('update');
        Route::get('/{vuzDivision}/delete', 'Admin\VuzDivisionController@destroy')->name('delete');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzDivisionController@store')->name('store');
    });
    Route::prefix('speciality')->name('speciality.')->group(function () {
        Route::get('/', 'AdminController@specialityIndex')->name('index');
        Route::get('/list', 'AdminController@specialityIndex')->name('list');
        Route::get('/create', 'AdminController@specialityCreate')->name('create');
        Route::post('/create', 'AdminController@specialityStore')->name('store');
        Route::get('/{speciality}', 'AdminController@specialityRead')->name('read');
        Route::get('/{speciality}/edit', 'AdminController@specialityEdit')->name('edit');
        Route::post('/{speciality}/edit', 'AdminController@specialityUpdate')->name('update');
        Route::get('/{speciality}/delete', 'AdminController@specialityDestroy')->name('delete');
        Route::post('/create', 'AdminController@specialityStore')->name('store');
    });
    Route::prefix('eduForm')->name('eduForm.')->group(function () {
        Route::get('/', 'AdminController@eduFormIndex')->name('index');
        Route::get('/list', 'AdminController@eduFormIndex')->name('list');
        Route::get('/create', 'AdminController@eduFormCreate')->name('create');
        Route::post('/create', 'AdminController@eduFormStore')->name('store');
        Route::get('/{eduForm}', 'AdminController@eduFormRead')->name('read');
        Route::get('/{eduForm}/edit', 'AdminController@eduFormEdit')->name('edit');
        Route::post('/{eduForm}/edit', 'AdminController@eduFormUpdate')->name('update');
        Route::get('/{eduForm}/delete', 'AdminController@eduFormDestroy')->name('delete');
    });

    Route::prefix('profile')->name('profile.')->group(function () {
        Route::get('/', 'AdminController@profileIndex')->name('index');
        Route::post('/', 'AdminController@profileUpdate')->name('update');
    });
    Route::prefix('post')->name('post.')->group(function () {
        Route::get('/{post}', 'Admin\PostController@read')->name('read');
        Route::get('/{post}/edit', 'Admin\PostController@edit')->name('edit');
        Route::post('/{post}/edit', 'Admin\PostController@update')->name('update');
        Route::get('/post}/delete', 'Admin\PostController@destroy')->name('delete');
        Route::get('/{parent_type}/{parent_id}', 'Admin\PostController@index')->name('index');
        Route::get('/{parent_type}/{parent_id}/list', 'Admin\PostController@index')->name('list');
        Route::get('/{parent_type}/{parent_id}/create', 'Admin\PostController@create')->name('create');
        Route::post('/{parent_type}/{parent_id}/create', 'Admin\PostController@store')->name('store');
    });
    Route::prefix('exam')->name('exam.')->group(function () {
        Route::get('/', 'AdminController@examIndex')->name('index');
        Route::get('/list', 'AdminController@examIndex')->name('list');
        Route::get('/create', 'AdminController@examCreate')->name('create');
        Route::post('/create', 'AdminController@examStore')->name('store');
        Route::get('/{exam}', 'AdminController@examRead')->name('read');
        Route::get('/{exam}/edit', 'AdminController@examEdit')->name('edit');
        Route::post('/{exam}/edit', 'AdminController@examUpdate')->name('update');
        Route::get('/{exam}/delete', 'AdminController@examDestroy')->name('delete');
    });
    Route::prefix('subject')->name('subject.')->group(function () {
        Route::get('/e{exam}/', 'AdminController@subjectIndex')->name('index');
        Route::get('/e{exam}/list', 'AdminController@subjectIndex')->name('list');
        Route::get('/e{exam}/create', 'AdminController@subjectCreate')->name('create');
        Route::post('/e{exam}/create', 'AdminController@subjectStore')->name('store');
        Route::get('/{subject}', 'AdminController@subjectRead')->name('read');
        Route::get('/{subject}/edit', 'AdminController@subjectEdit')->name('edit');
        Route::post('/{subject}/edit', 'AdminController@subjectUpdate')->name('update');
        Route::get('/{subject}/delete', 'AdminController@subjectDestroy')->name('delete');
    });
    Route::prefix('theme')->name('theme.')->group(function () {
        Route::get('/s{subject}/', 'AdminController@themeIndex')->name('index');
        Route::get('/s{subject}/list', 'AdminController@themeIndex')->name('list');
        Route::get('/s{subject}/create', 'AdminController@themeCreate')->name('create');
        Route::post('/s{subject}/create', 'AdminController@themeStore')->name('store');
        Route::get('/{theme}', 'AdminController@themeRead')->name('read');
        Route::get('/{theme}/edit', 'AdminController@themeEdit')->name('edit');
        Route::post('/{theme}/edit', 'AdminController@themeUpdate')->name('update');
        Route::get('/{theme}/delete', 'AdminController@themeDestroy')->name('delete');
    });
    Route::prefix('prot')->name('prot.')->group(function () {
        Route::get('/th{theme}/create', 'AdminController@protCreate')->name('create');
        Route::post('/th{theme}/create', 'AdminController@protStore')->name('store');
        Route::get('/{prot}', 'AdminController@protRead')->name('read');
        Route::get('/{prot}/edit', 'AdminController@protEdit')->name('edit');
        Route::post('/{prot}/edit', 'AdminController@protUpdate')->name('update');
        Route::get('/{prot}/delete', 'AdminController@protDestroy')->name('delete');
    });
    Route::prefix('page')->name('page.')->group(function () {
        Route::get('/create', 'AdminController@pageCreate')->name('create');
        Route::post('/create', 'AdminController@pageStore')->name('store');
        Route::get('/list', 'AdminController@pageIndex')->name('list');
        Route::get('/{page}', 'AdminController@pageRead')->name('read');
        Route::get('/{page}/edit', 'AdminController@pageEdit')->name('edit');
        Route::post('/{page}/edit', 'AdminController@pageUpdate')->name('update');
        Route::get('/{page}/delete', 'AdminController@pageDestroy')->name('delete');
        Route::get('/', 'AdminController@pageIndex')->name('index');
    });
    Route::prefix('media-size')->name('mediaSize.')->group(function () {
        Route::get('/', 'Admin\MediaSizeController@index')->name('index');
        Route::get('/list', 'Admin\MediaSizeController@index')->name('list');
        Route::get('/create', 'Admin\MediaSizeController@create')->name('create');

resources/views/admin/page/create.blade.php
@extends('layouts.admin',[
    'page_header'=>'Создать новую страницу'
])
@section('breadcrumb')
    <ol class="breadcrumb">
        <li><a href="{{route('admin.index')}}"><i class="fa fa-dashboard"></i> Домой</a></li>
        <li><a href="{{route('admin.page.list')}}"> Страницы</a></li>
        <li class="active">Создать</li>
    </ol>
@endsection
@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Создать новую страницу </h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            @component('admin/page/form',[
                'action'=>route('admin.page.store'),
                'formSubmitTitle' => 'Создать'
            ])

            @endcomponent
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@endsection
@section('scripts')
@endsection

resources/views/admin/page/edit.blade.php
@extends('layouts.admin',[
    'page_header'=>'Редактировать страницу'
])
@section('breadcrumb')
    <ol class="breadcrumb">
        <li><a href="{{route('admin.index')}}"><i class="fa fa-dashboard"></i> Домой</a></li>
        <li><a href="{{route('admin.page.list')}}"> Страницы</a></li>
        <li><a href="{{route('admin.page.read',[
            'page'=>$page->id
        ])}}">{{$page->title}}</a></li>
        <li class="active">Редактировать</li>
    </ol>
@endsection
@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Редактировать страницу </h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            @component('admin/page/form',[
                'action'=>route('admin.page.update',[
                    'page' => $page->id
                ]),
                'formSubmitTitle' => 'Сохранить',
                'formData' => $page
            ])

            @endcomponent
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@endsection
@section('scripts')
@endsection

resources/views/admin/page/form.blade.php
<form method="POST" action="{{$action}}" enctype="multipart/form-data">
    @csrf
    <div class="form-group row">
        <label for="status" class="col-md-4 col-form-label text-md-right">Статус</label>
        <div class="col-md-6">
            <select id="status" type="text" class="form-control{{ $errors->has('status') ? ' is-invalid' : '' }}" name="status" required>
                <option value="0" {{(old('status',$formData->status??0))==0?'selected':''}}> Черновик</option>
                <option value="1" {{(old('status',$formData->status??0))==1?'selected':''}}> Опубликовано</option>
            </select>
            @if ($errors->has('status'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('status') }}</strong>
                </span>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="title" class="col-md-4 col-form-label text-md-right">Заголовок страницы</label>
        <div class="col-md-6">
            <input id="title" type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ old('title',$formData->title ?? '')  }}" required autofocus>
            @if ($errors->has('title'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('title') }}</strong>
                </span>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="description" class="col-md-4 col-form-label text-md-right">Описание</label>
        <div class="col-md-6">
            <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" required>{{ old('description',$formData->description ?? '') }}</textarea>
            @if ($errors->has('description'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('description') }}</strong>
                </span>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="seo_keywords" class="col-md-4 col-form-label text-md-right">Ключевые слова</label>
        <div class="col-md-6">
            <input id="seo_keywords" type="text" class="form-control{{ $errors->has('seo_keywords') ? ' is-invalid' : '' }}" name="seo_keywords" value="{{ old('seo_keywords',$formData->seo_keywords ?? '')  }}" required autofocus>
            <span class="text-muted">Укажите через запятую</span>
            @if ($errors->has('seo_keywords'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('seo_keywords') }}</strong>
                </span>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="type" class="col-md-4 col-form-label text-md-right">Тип страницы</label>
        <div class="col-md-6">
            <select id="type" type="text" class="form-control{{ $errors->has('type') ? ' is-invalid' : '' }}" name="type" required>
                <option value="олимпиада" {{(old('type')??$formData->type??'')=='олимпиада'?'selected':''}}> Олимпиада </option>
                <option value="курс" {{(old('type')??$formData->type??'')=='олимпиада'?'selected':''}}> Курс </option>
                <option value="прочее" {{(old('type')??$formData->type??'')=='прочее'?'selected':''}}> Прочее </option>
            </select>
            @if ($errors->has('type'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('type') }}</strong>
                </span>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="context" class="col-md-4 col-form-label text-md-right">Содержимое</label>
        <div class="col-md-12">
            <textarea id="context" class="form-control{{ $errors->has('context') ? ' is-invalid' : '' }}" name="context">{{ old('context',$formData->context ?? '') }}</textarea>
            @if ($errors->has('context'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('context') }}</strong>
                </span>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="logo" class="col-md-4 col-form-label text-md-right">Логотип</label>
        <div class="col-md-6">
            <input type="file"  class="form-control custom-file-input{{ $errors->has('logo') ? ' is-invalid' : 'logo' }}" id="logo" name="logo" accept="image/jpeg,image/png">
            @if ($errors->has('logo'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('logo') }}</strong>
                </span>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="cover_image" class="col-md-4 col-form-label text-md-right">Обложка</label>
        <div class="col-md-6">
            <input type="file"  class="form-control custom-file-input{{ $errors->has('cover_image') ? ' is-invalid' : 'cover_image' }}" id="cover_image" name="cover_image" accept="image/jpeg,image/png">
            @if ($errors->has('cover_image'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('cover_image') }}</strong>
                </span>
            @endif
        </div>
    </div>
    <strong>{{ $errors->first() }}</strong>
    <div class="form-group row mb-0">
        <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
                {{ $formSubmitTitle ?? 'Отправить форму' }}
            </button>
        </div>
    </div>
</form>
<script src='/adminLTE/js/tinymce/tinymce.min.js'></script>
<script>
    var dfreeBodyConfig = {
        selector: '#context',
        menubar: false,
        height:300,
        plugins: [
            "advlist anchor autolink codesample colorpicker contextmenu fullscreen help image imagetools",
            " lists link media noneditable preview",
            " searchreplace table template textcolor visualblocks wordcount"
        ]
    };

    tinymce.init(dfreeBodyConfig);
</script>

resources/views/admin/page/index.blade.php
@extends('layouts.admin',[
    'page_header'=>'Страницы'
])
@section('breadcrumb')
    <ol class="breadcrumb">
        <li><a href="{{route('admin.index')}}"><i class="fa fa-dashboard"></i> Домой</a></li>
        <li class="active">Страницы</li>
    </ol>
@endsection
@section('content')
    <div>
        <a href="{{route('admin.page.create')}}" class="btn btn-success"><i class="fa fa-plus"></i> &nbsp; Добавить страницу</a>
    </div>
    <br>
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Список</h3>
        </div>
        <!-- /.box-header -->


        <div class="box-body">
            <form action="" class="form-inline">
                <div class="input-group">
                    <input type="search" class="form-control" placeholder="Поиск" name="s" value="{{\Request::get('s')}}">
                </div>
                <button class="btn btn-primary" type="submit">
                    <i class="fa fa-search"></i>
                </button>

            </form>
            <div class="table-responsive">
                <table class="data-table table table-bordered table-striped">
                    <col width="auto" span="4">
                    <col width="150">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th></th>
                        <th>Статус</th>
                        <th>Название</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($pages as $page)
                        <tr>
                            <th>{{$page->id}}</th>
                            <td>
                                @if($page->logo)
                                    <img style="max-width: 100px;" class="img-responsive" src="{{$page->logo}}" alt="">
                                @else
                                    -
                                @endif
                            </td>
                            <td>
                                {{$page->status==1?'Опубликовано':''}}
                                {{$page->status==0?'Черновик':''}}
                            </td>
                            <td>{{$page->title}}</td>
                            <td>
                                <a href="{{route('admin.page.read',[
                                    'page'=>$page->id
                                ])}}" class="btn btn-success"><i class="fa fa-eye"></i></a>
                                <a href="{{route('admin.page.edit',[
                                    'page'=>$page->id
                                ])}}" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                <a onclick="return confirm('Вы действительно хотите удалить страницу #{{$page->id}}?');" href="{{route('admin.page.delete',[
                                    'page'=>$page->id
                                ])}}" class="btn btn-danger"><i class="fa fa-times"></i></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <!-- /.box-body -->
        {{$pages->appends(['s' => \Request::get('s')])->links()}}
    </div>
    <!-- /.box -->
@endsection
@section('scripts')

@endsection

resources/views/admin/page/read.blade.php
@extends('layouts.admin',[
    'page_header'=>'Просмотр страницы'
])
@section('breadcrumb')
    <ol class="breadcrumb">
        <li><a href="{{route('admin.index')}}"><i class="fa fa-dashboard"></i> Домой</a></li>
        <li><a href="{{route('admin.page.list')}}"> Страницы</a></li>
        <li class="active">{{$page->title}}</li>
    </ol>
@endsection

@section('content')

    <div>
        <a href="{{route('admin.page.edit',[
                                '$page'=>$page->id
                            ])}}" class="btn btn-primary"><i class="fa fa-edit"></i> &nbsp; Редактировать </a>
        <a href="{{route('admin.post.list',[
                                'parent_type'=>'Page',
                                'parent_id'=>$page->id
                            ])}}" class="btn btn-primary"><i class="fa fa-file-text-o"></i> &nbsp;Записи </a>
        <a onclick="return confirm('Вы действительно хотите удалить эту страницу?');" href="{{route('admin.page.delete',[
                                'page'=>$page->id
                            ])}}" class="btn btn-danger"><i class="fa fa-times"></i> &nbsp; Удалить </a>
    </div>
    <br>
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Просмотр страницы: {{$page->name}} </h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>#</th>
                        <td>{{$page->id}}</td>
                    </tr>
                    <tr>
                        <th>Статус</th>
                        <td>
                            {{$page->status==1?'Опубликовано':''}}
                            {{$page->status==0?'Черновик':''}}
                        </td>
                    </tr>
                    <tr>
                        <th>Название</th>
                        <td>{{$page->title}}</td>
                    </tr>
                    <tr>
                        <th>Ссылка</th>
                        <td>{{$page->link}}</td>
                    </tr>
                    <tr>
                        <th>Описание</th>
                        <td>{{$page->description}}</td>
                    </tr>
                    <tr>
                        <th>Логотип</th>
                        <td>
                            @if($page->logo)
                                <img style="max-width: 150px;" class="img-responsive" src="{{$page->logo}}">
                            @else
                                Не загружен
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <th>Фоновое изображение</th>
                        <td>
                            @if($page->cover_image)
                                <img style="max-width: 300px;" class="img-responsive" src="{{$page->cover_image}}">
                            @else
                                Не загружено
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <th>Ключевые слова</th>
                        <td>{{$page->seo_keywords}}</td>
                    </tr>
                    <tr>
                        <th>Тип страницы</th>
                        <td>{{$page->type}}</td>
                    </tr>
                    <tr>
                        <th>Содержимое</th>
                        <td>{!!$page->context !!}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@endsection
@section('scripts')

@endsection