routes/web.php
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::domain('admin.penal.ga')->name('admin.')->middleware('verified','admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::prefix('organization')->name('organization.')->group(function () {
        Route::get('/', 'Admin\OrganizationController@index')->name('index');
        Route::get('/list', 'Admin\OrganizationController@index')->name('list');
        Route::get('/create', 'Admin\OrganizationController@create')->name('create');
        Route::post('/create', 'Admin\OrganizationController@store')->name('store');
        Route::get('/{organization}', 'Admin\OrganizationController@read')->name('read');
        Route::get('/{organization}/edit', 'Admin\OrganizationController@edit')->name('edit');
        Route::post('/{organization}/edit', 'Admin\OrganizationController@update')->name('update');
        Route::get('/{organization}/delete', 'Admin\OrganizationController@destroy')->name('delete');
        Route::post('/create', 'Admin\OrganizationController@store')->name('store');
        Route::prefix('vuz')->name('vuz.')->group(function(){
            Route::get('/{organization}/editProhodBalls', 'Admin\OrganizationController@vuzEditProhodBalls')->name('editProhodBalls');
            Route::post('/{organization}/updateProhodBalls', 'Admin\OrganizationController@vuzUpdateProhodBalls')->name('updateProhodBalls');
        });

    });
    /*Route::prefix('vuzFaculty')->name('vuz_faculty.')->group(function () {
        Route::get('/vuz/{vuz}', 'Admin\VuzFacultyController@index')->name('index');
        Route::get('/vuz/{vuz}/list', 'Admin\VuzFacultyController@index')->name('list');
        Route::get('/vuz/{vuz}/create', 'Admin\VuzFacultyController@create')->name('create');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzFacultyController@store')->name('store');
        Route::get('/{vuzFaculty}', 'Admin\VuzFacultyController@read')->name('read');
        Route::get('/{vuzFaculty}/edit', 'Admin\VuzFacultyController@edit')->name('edit');
        Route::post('/{vuzFaculty}/edit', 'Admin\VuzFacultyController@update')->name('update');
        Route::get('/{vuzFaculty}/delete', 'Admin\VuzFacultyController@destroy')->name('delete');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzFacultyController@store')->name('store');
    });*/
    Route::prefix('vuzDivision')->name('vuz_division.')->group(function () {
        Route::get('/vuz/{vuz}', 'Admin\VuzDivisionController@index')->name('index');
        Route::get('/vuz/{vuz}/list', 'Admin\VuzDivisionController@index')->name('list');
        Route::get('/vuz/{vuz}/create', 'Admin\VuzDivisionController@create')->name('create');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzDivisionController@store')->name('store');
        Route::get('/{vuzDivision}', 'Admin\VuzDivisionController@read')->name('read');
        Route::get('/{vuzDivision}/edit', 'Admin\VuzDivisionController@edit')->name('edit');
        Route::post('/{vuzDivision}/edit', 'Admin\VuzDivisionController@update')->name('update');
        Route::get('/{vuzDivision}/delete', 'Admin\VuzDivisionController@destroy')->name('delete');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzDivisionController@store')->name('store');
    });
    Route::prefix('speciality')->name('speciality.')->group(function () {
        Route::get('/', 'AdminController@specialityIndex')->name('index');
        Route::get('/list', 'AdminController@specialityIndex')->name('list');
        Route::get('/create', 'AdminController@specialityCreate')->name('create');
        Route::post('/create', 'AdminController@specialityStore')->name('store');
        Route::get('/{speciality}', 'AdminController@specialityRead')->name('read');
        Route::get('/{speciality}/edit', 'AdminController@specialityEdit')->name('edit');
        Route::post('/{speciality}/edit', 'AdminController@specialityUpdate')->name('update');
        Route::get('/{speciality}/delete', 'AdminController@specialityDestroy')->name('delete');
        Route::post('/create', 'AdminController@specialityStore')->name('store');
    });
    Route::prefix('eduForm')->name('eduForm.')->group(function () {
        Route::get('/', 'AdminController@eduFormIndex')->name('index');
        Route::get('/list', 'AdminController@eduFormIndex')->name('list');
        Route::get('/create', 'AdminController@eduFormCreate')->name('create');
        Route::post('/create', 'AdminController@eduFormStore')->name('store');
        Route::get('/{eduForm}', 'AdminController@eduFormRead')->name('read');
        Route::get('/{eduForm}/edit', 'AdminController@eduFormEdit')->name('edit');
        Route::post('/{eduForm}/edit', 'AdminController@eduFormUpdate')->name('update');
        Route::get('/{eduForm}/delete', 'AdminController@eduFormDestroy')->name('delete');
    });

    Route::prefix('profile')->name('profile.')->group(function () {
        Route::get('/', 'AdminController@profileIndex')->name('index');
        Route::post('/', 'AdminController@profileUpdate')->name('update');
    });
    Route::prefix('post')->name('post.')->group(function () {
        Route::get('/{post}', 'Admin\PostController@read')->name('read');
        Route::get('/{post}/edit', 'Admin\PostController@edit')->name('edit');
        Route::post('/{post}/edit', 'Admin\PostController@update')->name('update');
        Route::get('/post}/delete', 'Admin\PostController@destroy')->name('delete');
        Route::get('/{parent_type}/{parent_id}', 'Admin\PostController@index')->name('index');
        Route::get('/{parent_type}/{parent_id}/list', 'Admin\PostController@index')->name('list');
        Route::get('/{parent_type}/{parent_id}/create', 'Admin\PostController@create')->name('create');
        Route::post('/{parent_type}/{parent_id}/create', 'Admin\PostController@store')->name('store');
    });
    Route::prefix('exam')->name('exam.')->group(function () {
        Route::get('/', 'AdminController@examIndex')->name('index');
        Route::get('/list', 'AdminController@examIndex')->name('list');
        Route::get('/create', 'AdminController@examCreate')->name('create');
        Route::post('/create', 'AdminController@examStore')->name('store');
        Route::get('/{exam}', 'AdminController@examRead')->name('read');
        Route::get('/{exam}/edit', 'AdminController@examEdit')->name('edit');
        Route::post('/{exam}/edit', 'AdminController@examUpdate')->name('update');
        Route::get('/{exam}/delete', 'AdminController@examDestroy')->name('delete');
    });
    Route::prefix('subject')->name('subject.')->group(function () {
        Route::get('/e{exam}/', 'AdminController@subjectIndex')->name('index');
        Route::get('/e{exam}/list', 'AdminController@subjectIndex')->name('list');
        Route::get('/e{exam}/create', 'AdminController@subjectCreate')->name('create');
        Route::post('/e{exam}/create', 'AdminController@subjectStore')->name('store');
        Route::get('/{subject}', 'AdminController@subjectRead')->name('read');
        Route::get('/{subject}/edit', 'AdminController@subjectEdit')->name('edit');
        Route::post('/{subject}/edit', 'AdminController@subjectUpdate')->name('update');
        Route::get('/{subject}/delete', 'AdminController@subjectDestroy')->name('delete');
    });
    Route::prefix('theme')->name('theme.')->group(function () {
        Route::get('/s{subject}/', 'AdminController@themeIndex')->name('index');
        Route::get('/s{subject}/list', 'AdminController@themeIndex')->name('list');
        Route::get('/s{subject}/create', 'AdminController@themeCreate')->name('create');
        Route::post('/s{subject}/create', 'AdminController@themeStore')->name('store');
        Route::get('/{theme}', 'AdminController@themeRead')->name('read');
        Route::get('/{theme}/edit', 'AdminController@themeEdit')->name('edit');
        Route::post('/{theme}/edit', 'AdminController@themeUpdate')->name('update');
        Route::get('/{theme}/delete', 'AdminController@themeDestroy')->name('delete');
    });
    Route::prefix('prot')->name('prot.')->group(function () {
        Route::get('/th{theme}/create', 'AdminController@protCreate')->name('create');
        Route::post('/th{theme}/create', 'AdminController@protStore')->name('store');
        Route::get('/{prot}', 'AdminController@protRead')->name('read');
        Route::get('/{prot}/edit', 'AdminController@protEdit')->name('edit');
        Route::post('/{prot}/edit', 'AdminController@protUpdate')->name('update');
        Route::get('/{prot}/delete', 'AdminController@protDestroy')->name('delete');
    });
    Route::prefix('page')->name('page.')->group(function () {
        Route::get('/create', 'AdminController@pageCreate')->name('create');
        Route::post('/create', 'AdminController@pageStore')->name('store');
        Route::get('/list', 'AdminController@pageIndex')->name('list');
        Route::get('/{page}', 'AdminController@pageRead')->name('read');
        Route::get('/{page}/edit', 'AdminController@pageEdit')->name('edit');
        Route::post('/{page}/edit', 'AdminController@pageUpdate')->name('update');
        Route::get('/{page}/delete', 'AdminController@pageDestroy')->name('delete');
        Route::get('/', 'AdminController@pageIndex')->name('index');
    });
    Route::prefix('media-size')->name('mediaSize.')->group(function () {
        Route::get('/', 'Admin\MediaSizeController@index')->name('index');
        Route::get('/list', 'Admin\MediaSizeController@index')->name('list');
        Route::get('/create', 'Admin\MediaSizeController@create')->name('create');
        Route::post('/create', 'Admin\MediaSizeController@store')->name('store');
        Route::get('/{mediaSize}', 'Admin\MediaSizeController@read')->name('read');
        Route::get('/{mediaSize}/edit', 'Admin\MediaSizeController@edit')->name('edit');

app/Speciality.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Speciality extends Model
{
    protected $fillable=[
        'name','description', 'nps','parent'
    ];

    public function organizations(){
        return $this->belongsToMany('App\Organization');
    }
    public function children(){
        return $this->hasMany('App\Speciality','parent');
    }
}

resources/views/admin/speciality/create.blade.php
@extends('layouts.admin',[
    'page_header'=>'Создать новую специальность'
])

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Создать новую специальность </h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            @component('admin/speciality/form',[
                'action'=>route('admin.speciality.store'),
                'formSubmitTitle' => 'Создать'
            ])

            @endcomponent
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@endsection
@section('scripts')

@endsection

resources/views/admin/speciality/edit.blade.php
@extends('layouts.admin',[
    'page_header'=>'Редактировать специальность'
])

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Редактировать специальность </h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            @component('admin/speciality/form',[
                'action'=>route('admin.speciality.update',[
                    'speciality' => $speciality->id
                ]),
                'formSubmitTitle' => 'Сохранить',
                'formData' => $speciality
            ])

            @endcomponent
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@endsection
@section('scripts')

@endsection

resources/views/admin/speciality/form.blade.php
<form method="POST" action="{{$action}}">
    @csrf

    <div class="form-group row">
        <label for="name" class="col-md-4 col-form-label text-md-right">Название специальности</label>
        <div class="col-md-6">
            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name',$formData->name ?? '')  }}" required autofocus>
            @if ($errors->has('name'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="nps" class="col-md-4 col-form-label text-md-right">Код специальности (НПС)</label>
        <div class="col-md-6">
            <input id="nps" type="text" class="form-control{{ $errors->has('nps') ? ' is-invalid' : '' }}" name="nps" value="{{ old('nps',$formData->nps ?? '')  }}" required autofocus>
            @if ($errors->has('nps'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('nps') }}</strong>
                </span>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="description" class="col-md-4 col-form-label text-md-right">Описание специальности</label>
        <div class="col-md-12">
            <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" required>{{ old('description',$formData->description ?? '') }}</textarea>
            @if ($errors->has('description'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('description') }}</strong>
                </span>
            @endif
        </div>
    </div>
        <div class="form-group row mb-0">
        <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
                {{ $formSubmitTitle ?? 'Отправить форму' }}
            </button>
        </div>
    </div>
</form>

resources/views/admin/speciality/index.blade.php
@extends('layouts.admin',[
    'page_header'=>'Специальности'
])

@section('content')
    <div>
        <a href="{{route('admin.speciality.create')}}" class="btn btn-success"><i class="fa fa-plus"></i> &nbsp; Добавить специальность</a>
    </div>
    <br>
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Список</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table class="data-table table table-bordered table-striped">
                <col width="auto" span="4">
                <col width="150">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Название</th>
                    <th>Описание</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($specialities as $speciality)
                    <tr>
                        <th>{{$speciality->nps}}</th>
                        <td>{{$speciality->name}}</td>
                        <td>{{$speciality->description}}</td>
                        <td>
                            <a href="{{route('admin.speciality.read',[
                                'speciality'=>$speciality->id
                            ])}}" class="btn btn-success"><i class="fa fa-eye"></i></a>
                            <a href="{{route('admin.speciality.edit',[
                                'speciality'=>$speciality->id
                            ])}}" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                            <a onclick="return confirm('Вы действительно хотите удалить специальность #{{$speciality->name}}?');" href="{{route('admin.speciality.delete',[
                                'speciality'=>$speciality->id
                            ])}}" class="btn btn-danger"><i class="fa fa-times"></i></a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@endsection
@section('scripts')
    <!-- page script -->
    <script>
        $(function () {
            $('.data-table').DataTable({
                'paging'      : true,
                'lengthChange': true,
                'searching'   : true,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : true
            })
        })
    </script>
@endsection

resources/views/admin/speciality/read.blade.php
@extends('layouts.admin',[
    'page_header'=>'Просмотр специальности'
])

@section('content')

    <div>
        <a href="{{route('admin.speciality.edit',[
                                'speciality'=>$speciality->id
                            ])}}" class="btn btn-primary"><i class="fa fa-edit"></i> &nbsp; Редактировать </a>
        <a onclick="return confirm('Вы действительно хотите удалить эту специальность?');" href="{{route('admin.speciality.delete',[
                                'speciality'=>$speciality->id
                            ])}}" class="btn btn-danger"><i class="fa fa-times"></i> &nbsp; Удалить </a>
    </div>
    <br>
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Просмотр специальности {{$speciality->name}} </h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>#</th>
                        <td>{{$speciality->id}}</td>
                    </tr>
                    <tr>
                        <th>НПС</th>
                        <td>{{$speciality->nps}}</td>
                    </tr>
                    <tr>
                        <th>Название</th>
                        <td>{{$speciality->name}}</td>
                    </tr>
                    <tr>
                        <th>Описание</th>
                        <td>{{$speciality->description}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@endsection
@section('scripts')

@endsection