routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::domain('admin.penal.ga')->name('admin.')->middleware('verified','admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::prefix('organization')->name('organization.')->group(function () {
        Route::get('/', 'Admin\OrganizationController@index')->name('index');
        Route::get('/list', 'Admin\OrganizationController@index')->name('list');
        Route::get('/create', 'Admin\OrganizationController@create')->name('create');
        Route::post('/create', 'Admin\OrganizationController@store')->name('store');
        Route::get('/{organization}', 'Admin\OrganizationController@read')->name('read');
        Route::get('/{organization}/edit', 'Admin\OrganizationController@edit')->name('edit');
        Route::post('/{organization}/edit', 'Admin\OrganizationController@update')->name('update');
        Route::get('/{organization}/delete', 'Admin\OrganizationController@destroy')->name('delete');
        Route::post('/create', 'Admin\OrganizationController@store')->name('store');
        Route::prefix('vuz')->name('vuz.')->group(function(){
            Route::get('/{organization}/editProhodBalls', 'Admin\OrganizationController@vuzEditProhodBalls')->name('editProhodBalls');
            Route::post('/{organization}/updateProhodBalls', 'Admin\OrganizationController@vuzUpdateProhodBalls')->name('updateProhodBalls');
        });

    });
    /*Route::prefix('vuzFaculty')->name('vuz_faculty.')->group(function () {
        Route::get('/vuz/{vuz}', 'Admin\VuzFacultyController@index')->name('index');
        Route::get('/vuz/{vuz}/list', 'Admin\VuzFacultyController@index')->name('list');
        Route::get('/vuz/{vuz}/create', 'Admin\VuzFacultyController@create')->name('create');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzFacultyController@store')->name('store');
        Route::get('/{vuzFaculty}', 'Admin\VuzFacultyController@read')->name('read');
        Route::get('/{vuzFaculty}/edit', 'Admin\VuzFacultyController@edit')->name('edit');
        Route::post('/{vuzFaculty}/edit', 'Admin\VuzFacultyController@update')->name('update');
        Route::get('/{vuzFaculty}/delete', 'Admin\VuzFacultyController@destroy')->name('delete');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzFacultyController@store')->name('store');
    });*/
    Route::prefix('vuzDivision')->name('vuz_division.')->group(function () {
        Route::get('/vuz/{vuz}', 'Admin\VuzDivisionController@index')->name('index');
        Route::get('/vuz/{vuz}/list', 'Admin\VuzDivisionController@index')->name('list');
        Route::get('/vuz/{vuz}/create', 'Admin\VuzDivisionController@create')->name('create');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzDivisionController@store')->name('store');
        Route::get('/{vuzDivision}', 'Admin\VuzDivisionController@read')->name('read');
        Route::get('/{vuzDivision}/edit', 'Admin\VuzDivisionController@edit')->name('edit');
        Route::post('/{vuzDivision}/edit', 'Admin\VuzDivisionController@update')->name('update');
        Route::get('/{vuzDivision}/delete', 'Admin\VuzDivisionController@destroy')->name('delete');
        Route::post('/vuz/{vuz}/create', 'Admin\VuzDivisionController@store')->name('store');
    });
    Route::prefix('speciality')->name('speciality.')->group(function () {
        Route::get('/', 'AdminController@specialityIndex')->name('index');
        Route::get('/list', 'AdminController@specialityIndex')->name('list');
        Route::get('/create', 'AdminController@specialityCreate')->name('create');
        Route::post('/create', 'AdminController@specialityStore')->name('store');
        Route::get('/{speciality}', 'AdminController@specialityRead')->name('read');
        Route::get('/{speciality}/edit', 'AdminController@specialityEdit')->name('edit');
        Route::post('/{speciality}/edit', 'AdminController@specialityUpdate')->name('update');
        Route::get('/{speciality}/delete', 'AdminController@specialityDestroy')->name('delete');
        Route::post('/create', 'AdminController@specialityStore')->name('store');
    });
    Route::prefix('eduForm')->name('eduForm.')->group(function () {
        Route::get('/', 'AdminController@eduFormIndex')->name('index');
        Route::get('/list', 'AdminController@eduFormIndex')->name('list');
        Route::get('/create', 'AdminController@eduFormCreate')->name('create');
        Route::post('/create', 'AdminController@eduFormStore')->name('store');
        Route::get('/{eduForm}', 'AdminController@eduFormRead')->name('read');
        Route::get('/{eduForm}/edit', 'AdminController@eduFormEdit')->name('edit');
        Route::post('/{eduForm}/edit', 'AdminController@eduFormUpdate')->name('update');
        Route::get('/{eduForm}/delete', 'AdminController@eduFormDestroy')->name('delete');
    });

    Route::prefix('profile')->name('profile.')->group(function () {
        Route::get('/', 'AdminController@profileIndex')->name('index');
        Route::post('/', 'AdminController@profileUpdate')->name('update');
    });
    Route::prefix('post')->name('post.')->group(function () {
        Route::get('/{post}', 'Admin\PostController@read')->name('read');
        Route::get('/{post}/edit', 'Admin\PostController@edit')->name('edit');
        Route::post('/{post}/edit', 'Admin\PostController@update')->name('update');
        Route::get('/post}/delete', 'Admin\PostController@destroy')->name('delete');
        Route::get('/{parent_type}/{parent_id}', 'Admin\PostController@index')->name('index');
        Route::get('/{parent_type}/{parent_id}/list', 'Admin\PostController@index')->name('list');
        Route::get('/{parent_type}/{parent_id}/create', 'Admin\PostController@create')->name('create');
        Route::post('/{parent_type}/{parent_id}/create', 'Admin\PostController@store')->name('store');
    });
    Route::prefix('exam')->name('exam.')->group(function () {
        Route::get('/', 'AdminController@examIndex')->name('index');
        Route::get('/list', 'AdminController@examIndex')->name('list');
        Route::get('/create', 'AdminController@examCreate')->name('create');
        Route::post('/create', 'AdminController@examStore')->name('store');
        Route::get('/{exam}', 'AdminController@examRead')->name('read');
        Route::get('/{exam}/edit', 'AdminController@examEdit')->name('edit');
        Route::post('/{exam}/edit', 'AdminController@examUpdate')->name('update');
        Route::get('/{exam}/delete', 'AdminController@examDestroy')->name('delete');
    });
    Route::prefix('subject')->name('subject.')->group(function () {
        Route::get('/e{exam}/', 'AdminController@subjectIndex')->name('index');
        Route::get('/e{exam}/list', 'AdminController@subjectIndex')->name('list');
        Route::get('/e{exam}/create', 'AdminController@subjectCreate')->name('create');
        Route::post('/e{exam}/create', 'AdminController@subjectStore')->name('store');
        Route::get('/{subject}', 'AdminController@subjectRead')->name('read');
        Route::get('/{subject}/edit', 'AdminController@subjectEdit')->name('edit');
        Route::post('/{subject}/edit', 'AdminController@subjectUpdate')->name('update');
        Route::get('/{subject}/delete', 'AdminController@subjectDestroy')->name('delete');
    });
    Route::prefix('theme')->name('theme.')->group(function () {
        Route::get('/s{subject}/', 'AdminController@themeIndex')->name('index');
        Route::get('/s{subject}/list', 'AdminController@themeIndex')->name('list');
        Route::get('/s{subject}/create', 'AdminController@themeCreate')->name('create');
        Route::post('/s{subject}/create', 'AdminController@themeStore')->name('store');
        Route::get('/{theme}', 'AdminController@themeRead')->name('read');
        Route::get('/{theme}/edit', 'AdminController@themeEdit')->name('edit');
        Route::post('/{theme}/edit', 'AdminController@themeUpdate')->name('update');
        Route::get('/{theme}/delete', 'AdminController@themeDestroy')->name('delete');
    });
    Route::prefix('prot')->name('prot.')->group(function () {
        Route::get('/th{theme}/create', 'AdminController@protCreate')->name('create');
        Route::post('/th{theme}/create', 'AdminController@protStore')->name('store');
        Route::get('/{prot}', 'AdminController@protRead')->name('read');
        Route::get('/{prot}/edit', 'AdminController@protEdit')->name('edit');
        Route::post('/{prot}/edit', 'AdminController@protUpdate')->name('update');
        Route::get('/{prot}/delete', 'AdminController@protDestroy')->name('delete');
    });
    Route::prefix('page')->name('page.')->group(function () {
        Route::get('/create', 'AdminController@pageCreate')->name('create');
        Route::post('/create', 'AdminController@pageStore')->name('store');
        Route::get('/list', 'AdminController@pageIndex')->name('list');
        Route::get('/{page}', 'AdminController@pageRead')->name('read');
        Route::get('/{page}/edit', 'AdminController@pageEdit')->name('edit');
        Route::post('/{page}/edit', 'AdminController@pageUpdate')->name('update');
        Route::get('/{page}/delete', 'AdminController@pageDestroy')->name('delete');
        Route::get('/', 'AdminController@pageIndex')->name('index');
    });
    Route::prefix('media-size')->name('mediaSize.')->group(function () {
        Route::get('/', 'Admin\MediaSizeController@index')->name('index');
        Route::get('/list', 'Admin\MediaSizeController@index')->name('list');
        Route::get('/create', 'Admin\MediaSizeController@create')->name('create');

app/Vuz.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vuz extends Model
{
    protected $fillable=[
      'id','city','address','min_ball','budget',
      'site','hostel','military'
    ];

    public function organization(){
        return $this->hasOne('App\Organization', 'id');
    }

    public function prohodBalls(){
        return $this->hasMany('App\ProhodBall');
    }
    public function prohod_ball(){
        return intval($this->prohodBalls()->where('ball','>',0)->avg('ball'));
    }
    public function budgetplaces(){
        return $this->prohodBalls()->sum('budgetplaces');
    }
    public function divisions(){
        return $this->hasMany('App\VuzDivision','vuz_id');
    }

}

app/Http/Controllers/VuzController.php
<?php

namespace App\Http\Controllers;

use App\ProhodBall;
use App\Speciality;
use App\Vuz;
use App\VuzDivision;
use App\VuzFaculty;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class VuzController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $vuzs=Vuz::join('organizations', 'vuzs.id', '=', 'organizations.id')->where('status', '=', 1);
        if(\Request::get('s')) $vuzs->whereHas('organization', function ($query) {
            $query->search(\Request::get('s'));
        });

        if($request -> get ('filter')=='on'){
            if($ball=$request->get('ball')){
                $vuzs=$vuzs->where('min_ball','<=',$ball+10);
            }
            if($city=$request->get('city')){
                $vuzs=$vuzs->where('city','LIKE',$city);
            }
            if($specialities=$request->get('specialties')){
                $vuzs=$vuzs->whereHas('organization.specialities', function ($query) use($specialities) {
                    $query->where('speciality_id', '=', $specialities);
                });
            }
            if($hostel=$request->get('hostel')=='on'){
                $vuzs=$vuzs->where('hostel','=',1);
            }
            if($military=$request->get('military')=='on'){
                $vuzs=$vuzs->where('military','=',1);
            }

            if($region=$request->get('region')){
                $vuzs=$vuzs->where('region','LIKE',$region);
            }
        }
        if(!\Request::get('specialities')){
            $vuzs = $vuzs
                /*->join( 'reviews', 'reviews.organization_id', '=', 'vuzs.id' )
                ->groupBy( 'vuzs.id' )
                ->select( 'vuzs.id', DB::raw( 'AVG( reviews.rating )' ) )*/
                ->orderByDesc('views');
        }else{
            $speciality = $request->get('specialities');

            $speciality = Speciality::find($speciality);
            if(!$speciality) return abort(404);
            $ch = $speciality->children()->select('id')->get();
            $specialities =[];
            array_push($specialities,$speciality->id);
            foreach($ch as $i){
                array_push($specialities,$i->id);
            }

            $vuzs = $vuzs->where('status', '=', 1)
                ->join('prohod_balls', 'vuzs.id', '=', 'prohod_balls.vuz_id')
                ->whereIn('speciality_id',$specialities)
                ->whereNotNull('ball')
                ->orderByDesc('views')
                ->orderBy('ball')
                ->groupBy('vuz_id')
                ->join('specialities', 'prohod_balls.speciality_id', '=', 'specialities.id')
                ->select('prohod_balls.*','specialities.*','vuzs.*','organizations.*','specialities.name as speciality_name','specialities.description as speciality_description');

            //dd($vuzs->limit(10)->get()[0]);
        }

        return view('Vuz/index',[
           'vuzs'=>$vuzs->orderByDesc('logo_image')->paginate(20)
        ]);
    }


    public function show(Vuz $vuz)
    {
        $vuz->organization()->increment('views');
        return view('Vuz/read',[
            'vuz'=>$vuz
        ]);
    }
    public function showTab(Vuz $vuz, $tab)
    {
        if($tab=='about') return view('Vuz/read',[
            'vuz'=>$vuz
        ]);
        else if ($tab=='map') return view('Vuz/map',[
            'vuz'=>$vuz
        ]);
        else if ($tab=='posts') return view('Vuz/posts',[
            'vuz'=>$vuz
        ]);
        else if ($tab=='reviews') return view('Vuz/reviews',[
            'vuz'=>$vuz
        ]);
        else if ($tab=='balls') return view('Vuz/balls',[
            'vuz'=>$vuz
        ]);
        else if ($tab=='structure') return view('Vuz/structure',[
            'vuz'=>$vuz
        ]);
        abort(404);
    }
    public function showFaculty(VuzFaculty $faculty)
    {
        return view('Vuz/faculty',[
            'faculty'=>$faculty
        ]);
    }
    public function showDivision(VuzDivision $division)
    {
        //dd($division->vuz_faculty);
        return view('Vuz/division',[
            'division'=>$division
        ]);
    }

}

resources/views/Vuz/balls.blade.php
@extends('layouts.app')
@section('head')
    <title>Проходные баллы ВУЗа {{$vuz->organization->name}} на Пенале</title>
    <meta description="На Пенале Вы можете познакомиться с {{$vuz->organization->name}}. {{$vuz->organization->description}}">
@endsection
@section('content')

    @component('Vuz/header',[
        'vuz'=>$vuz,
        'current_page'=>'balls'
    ])
    @endcomponent
    <div class="container">
        <table class="table table-bordered table-sm table-responsive">
            <thead>
            <tr>
                <th>НПС</th>
                <th>Специальность</th>
                <th>Подразделение</th>
                <th>Бюджет</th>
                <th>Платно</th>
                <th>Необходимые предметы</th>
                <th>Год</th>
            </tr>
            </thead>
            <tbody>
            @foreach(\App\Speciality::all() as $speciality)
                @if(count($prohodBalls=$vuz->prohodBalls()->where('speciality_id',$speciality->id)->orderBy('year', 'desc')->orderBy('division_id', 'desc')->get()))

                    @foreach($prohodBalls as $index => $prohodBall)
                        <tr>
                            @if($index===0)
                                <td rowspan="{{count($prohodBalls) - $index}}">{{$speciality->nps}}</td>
                                <th rowspan="{{count($prohodBalls) - $index}}">{{$speciality->name}}</th>
                            @endif
                            <td>
                                @if($prohodBall->division)
                                <a class="teal-link" data-toggle="tooltip" href="{{route('vuz.division.read',[
                                    'division'=>$prohodBall->division->id
                                ])}}" title="{{$prohodBall->division->name}}"> {{$prohodBall->division->short_name ?? $prohodBall->division->name}} </a>
                                @endif
                            </td>
                            <td>
                                @if($prohodBall->ball)
                                    {{$prohodBall->ball}} балла <br>
                                    {{$prohodBall->budgetplaces}} мест
                                @else
                                    -
                                @endif
                            </td>
                            <td>
                                @if($prohodBall->ballpayed)
                                    {{$prohodBall->ballpayed}} балла <br>
                                    {{$prohodBall->paidplaces}} мест
                                @else
                                    -
                                @endif

                            </td>
                            <td>{{$prohodBall->subjects}}</td>
                            <td>{{$prohodBall->year}}</td>
                        </tr>
                    @endforeach
                @endif
            @endforeach
            {{--@if(!$i)
                @foreach($prohodBalls as $index => $prohodBall)
                    <tr>
                        @if($index===0)
                            <td rowspan="{{count($prohodBalls) - $index}}">{{$speciality->nps}}</td>
                            <th rowspan="{{count($prohodBalls) - $index}}">{{$speciality->name}}</th>
                        @endif

                        <td>
                            <a class="teal-link" href="{{route('vuz.division.read',[
                                    'division'=>$prohodBall->division->vuz_faculty->id
                                ])}}"> {{$prohodBall->division->vuz_faculty->short_name}} </a>
                        </td>
                        <td>
                            <a class="teal-link" href="{{route('vuz.division.read',[
                                    'division'=>$prohodBall->division->id
                                ])}}"> {{$prohodBall->division->short_name}}. {{$prohodBall->division->name}} </a>
                        </td>
                        <td>{{$prohodBall->ball}}</td>
                        <td>{{$prohodBall->subjects}}</td>
                        <td>{{$prohodBall->year}}</td>
                    </tr>
                @endforeach
            @endif--}}
            </tbody>
        </table>
    </div>



@endsection
@section('scripts')
@endsection

resources/views/Vuz/division.blade.php
@extends('layouts.app')
@section('head')
    <title>Кафедра {{$division->name}} ВУЗа {{$division->vuz->organization->name}} на Пенале</title>
    <meta description="На Пенале Вы можете познакомиться с {{$division->name}}">
@endsection
@section('content')
    <div class="fullblock mb-5" style="background-image:linear-gradient(#0007,#0009),url('/img/bg-organization.png');">
        <div class="container pt-5 pb-5">
            <p class="mb-2">Подразделение</p>
            <h1 class="mb-4">{{$division->name}}</h1>
            <p>
                <span class="mr-5">ВУЗ: </span> <a class="teal-btn btn btn-sm" href="{{route('vuz.read',[
            'vuz'=> $division->vuz->id
        ])}}">{{$division->vuz->organization->name}}</a>
            </p>
            @if($division->parent_division)
            <p>
                <span class="mr-5">Родительское подразделение: </span> <a class="teal-btn btn btn-sm" href="{{route('vuz.division.read',[
            'faculty'=> $division->parent_division->id
        ])}}">{{$division->parent_division->name}} ({{$division->parent_division->short_name}})</a>
            </p>
            @endif
            <p>
                <span class="mr-5">Короткое название подразделения:</span> {{$division->short_name}}
            </p>
        </div>
    </div>
    <div class="container mt-5">
        <p class="mb-5">{{$division->description}}</p>

        <article>
            {!! $division->about !!}
        </article>
        @if(count($prohodBalls=$division->allProhodBalls()->orderBy('year', 'desc')->get()))
            <div>
                <h2>Проходные баллы</h2>
                <table class="table table-bordered fixed-thead">
                    <thead>
                        <tr>
                            <th>
                                НПС
                            </th>
                            <th>
                                Подразделение
                            </th>
                            <th>
                                Специальность
                            </th>

                            <th>
                                Балл
                            </th>

                            <th>
                                Необходимые предметы
                            </th>
                            <th>
                                Год
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                            @foreach($prohodBalls as $index => $prohodBall)
                                <tr>
                                    <td>{{$prohodBall->speciality->nps}}</td>
                                    <td>
                                        <a class="teal-link" href="{{route('vuz.division.read',[
                                            'division'=>$prohodBall->division->id
                                        ])}}"> {{$prohodBall->division->name}} </a>
                                    </td>
                                    <td>{{$prohodBall->speciality->name}}</td>
                                    <td>{{$prohodBall->ball}}</td>
                                    <td>{{$prohodBall->subjects}}</td>
                                    <td>{{$prohodBall->year}}</td>
                                </tr>
                            @endforeach
                    </tbody>
                </table>
            </div>
        @endif

        @if(count($division->children))
            <div class="mb-3">
                <h2>Дочерние подразделения</h2>
                @foreach($division->children as $division)
                    <li>
                        <a class="teal-link" href="{{route('vuz.division.read',[
                                    'division'=>$division->id
                                ])}}"> Подразделение "{{$division->name}}" ({{$division->short_name}}) </a>
                    </li>
                @endforeach
            </div>
        @elseif($division->parent_division)
            <div class="mb-3">
                <h2>Другие подразделения</h2>
                @foreach($division->parent_division->children()->where('id','!=',$division->id)->get() as $division)
                    <li>
                        <a class="teal-link" href="{{route('vuz.division.read',[
                                    'division'=>$division->id
                                ])}}"> Подразделение "{{$division->name}}" ({{$division->short_name}}) </a>
                    </li>
                @endforeach
            </div>
        @else
            <div class="mb-3">
                <h2>Другие подразделения</h2>
                @foreach($division->vuz->divisions()->where('id','!=',$division->id)->whereNull('parent')->get() as $division)
                    <li>
                        <a class="teal-link" href="{{route('vuz.division.read',[
                                    'division'=>$division->id
                                ])}}"> Подразделение "{{$division->name}}" ({{$division->short_name}}) </a>
                    </li>
                @endforeach
            </div>
        @endif
    </div>

@endsection
@section('scripts')

@endsection

resources/views/Vuz/index.blade.php
@extends('layouts.app')
@section('head')
    <title>ВУЗы на Пенале</title>

@endsection
@section('content')
    <div class="fullblock mbb" style="background-image:linear-gradient(#0007,#0009),url(/img/bg-vuz.jpg);">
        <div class="container ma">
            <h1 class="display-4 mt-4 mb-4" data-aos="fade-right"> ВУЗы</h1>
        </div>
    </div>
    <div class="row container ma">
        <div class="col-12">
            <p class="text-center"><b>Фильтр ВУЗов</b></p>
            <form>
                <div class="form-group">
                    <label>Поиск</label>
                    <input class="form-control" placeholder="Введите ваш запрос" name="s" value="{{\Request::get('s')}}">
                </div>
                <div class="form-group">
                    <input id="check_hostel" type="checkbox" name="hostel" {{\Request::get('hostel')=='on'?'checked':''}}>
                    <label for="check_hostel">Общежитие</label>
                </div>
                <div class="form-group">
                    <input id="check_military" type="checkbox" name="military" {{\Request::get('military')=='on'?'checked':''}}>
                    <label for="check_military">Военная кафедра</label>
                </div>

                <div class="form-group">
                    <label>Специальность</label>
                    <select class="form-control" name="specialities">
                        <option value="">Не выбрано</option>
                        @foreach(\App\Speciality::whereNull('parent')->get() as $speciality)
                            <option value="{{$speciality->id}}" {{\Request::get('specialities')==$speciality->id ?'selected':''}}>{{$speciality->name}} ({{$speciality->nps}})</option>
                        @endforeach

                    </select>
                </div>
                <div class="form-group">
                    <label>Регион</label>
                    <select class="form-control" name="region">
                        <option value="">Не выбрано</option>
                        @foreach(\App\Organization::groupBy('region')->select('region',DB::raw(' COUNT(*) AS `count`'))->orderByDesc('count')->get() as $region)
                            <option value="{{$region->region}}" {{\Request::get('region')!=""&&\Request::get('region')==$region->region ?'selected':''}}>{{$region->region}}</option>
                        @endforeach

                    </select>
                </div>
                <button type="submit" class="btn teal-btn d-block" name="filter" value="on" style="width: 100%;">Подобрать</button>
            </form>
        </div>
    </div>
    <div class="container" >
        <table class="table table-hover text-center table-sm align-middle table-bordered table-responsive" id="results">
            <colgroup width="75">
            </colgroup><thead>
            <tr>
                <th colspan="2">ВУЗ</th>
                <th>Проход<wbr>ной балл</th>
                <th>Бюджет<wbr>ных мест</th>
                <th>Обще<wbr>житие </th>
                <th>Военная кафедра</th>
                <th>Регион</th>
            </tr>
            </thead>
            <tbody>
            @foreach($vuzs as $vuz)
                <?php
                $organization=$vuz;
                ?>
                <tr id="post-49">
                    <td style="border-right:none;" @if($organization->ball) rowspan="2" @endif>
                        <img src="{{$organization->logo_image}}" alt="">
                    </td>
                    <td class="text-left align-middle" style="border-left:none;">
                        <a href="{{route('vuz.read',[
                                'vuz' => $vuz->id
                            ])}}" title="Подробнее о {{$organization->abbr}}" style="text-decoration:none;">
                            <p>
                                <b>
                                    {{$organization->abbr}}
                                </b>
                                <br>
                                {{$organization->name}}
                            </p>
                        </a>
                    </td>
                    {{--<td>{{$vuz->city}}</td>--}}
                    <td>{{$vuz->prohod_ball()}}</td>
                    <td>{{$vuz->budgetplaces()}}</td>

                    <td @if($organization->ball) rowspan="2" @endif>
                        @if($vuz->hostel)
                            <i class="fas fa-check-circle fa-2x text-success"></i>
                        @endif
                    </td>
                    <td @if($organization->ball) rowspan="2" @endif>
                        @if($vuz->military)
                            <i class="fas fa-check-circle fa-2x text-success"></i>
                        @endif
                    </td>
                    <td @if($organization->ball) rowspan="2" @endif>
                        {{$organization->region}}
                    </td>
                </tr>
                @if($organization->ball)
                    <tr>
                        <td class="text-left align-middle">
                            <b>{{$organization->speciality_name}}</b>
                            <a href="{{route('vuz.showTab',[
                                'vuz'=>$vuz->id,
                                'tab'=>'balls'
                            ])}}#tabs" class="teal-link">Показать ещё</a>
                        </td>
                        <td>
                            {{$organization->ball}}
                        </td>
                        <td>
                            {{$organization->budgetplaces}}
                        </td>
                    </tr>
                @endif
            @endforeach


            </tbody>
        </table>
    </div>
    {{$vuzs->appends([
            's' => \Request::get('s'),
            'military' => \Request::get('military'),
            'hostel' => \Request::get('hostel'),
            'filter' => 'on',
            'specialities' => \Request::get('specialities'),
            'region' => \Request::get('region')
            ])->links()}}

@endsection
@section('scripts')

    <script>

        document.addEventListener('DOMContentLoaded',function(){
            var filter = {{\Request::get('filter')?'true':'false'}};
            if(filter){
                window.scrollTo(0,document.querySelector('table').offsetTop-100)
            }
        });

    </script>
@endsection

resources/views/Vuz/posts.blade.php
@extends('layouts.app')
@section('head')
    <title>Новости и записи ВУЗа {{$vuz->organization->name}} на Пенале</title>
    <meta description="На Пенале Вы можете познакомиться с {{$vuz->organization->name}}. {{$vuz->organization->description}}">
@endsection
@section('content')

    @component('Vuz/header',[
        'vuz'=>$vuz,
        'current_page'=>'posts'
    ])
    @endcomponent

    <div class="container ma row">
        @foreach(($posts=$vuz->organization->posts()->latest()->paginate(10)) as $post)
            @include('shared.post',[
            'post'=>$post
            ])
        @endforeach
        @if(!count($posts))
            <div class="alert alert-warning col-12">
                К сожалению, у данного ВУЗа записей ещё нет.
            </div>
        @endif
    </div>
    {{$posts->links()}}
@endsection